#image: node:latest
stages:
  - docker-build
  - deploy

cache:
  paths:
  - node_modules/

docker build:
  stage: docker-build
  script:
    - docker-compose build
    - docker-compose push
  tags:
    - shell-build
#  only:
#    - master

#dev deploy:
#  stage: deploy
#  script:
#    - docker-compose pull
#    - docker-compose up -d
#  tags:
#    - deploy-dev
#  only:
#    - master
