version: '3'
services:
  discovery:
    image: lomocc/discovery
    container_name: discovery
    restart: always
    privileged: true
    build: .
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: "bridge"
